### ISSUE TITLE
Priv'd intents requirements missing from README

### ISSUE THREAD

**Issue by dylanh724** [jakobdylanc/gpt-discord#5]
On start:

```py
 python gpt-discord.py
2023-11-14 15:59:27.105 INFO: logging in using static token
Traceback (most recent call last):
  File "gpt-discord.py", line 110, in <module>
    if __name__ == "__main__": asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "gpt-discord.py", line 109, in main
    async def main(): await discord_client.start(os.environ["DISCORD_BOT_TOKEN"])
  File "/home/someUser/.local/lib/python3.8/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/home/someUser/.local/lib/python3.8/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
2023-11-14 15:59:27.884 ERROR: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1880b31220>, 36723372.991516)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f187fd64e80>
```

Which intents do we need aside from ` "message content intent"` (already checked)?
![image](https://github.com/jakobdylanc/gpt-discord/assets/8840024/739c4dd3-797a-409e-817e-c7056f5e33a9)

**Comment by dylanh724** [comment]
Used some deduction here: Oddly, it requires *ALL* intents enabled. How come? I thought this bot only uses message.

**Comment by jakobdylanc** [comment]
Good catch, thanks! Just pushed a fix.
