### ISSUE TITLE
chat/completions HTTP 404

### ISSUE THREAD

**Issue by dylanh724** [jakobdylanc/gpt-discord#6]
I pinged gpt "Hello", which crashed the bot:

```py
$ python gpt-discord.py
2023-11-14 16:12:39.884 INFO: logging in using static token
2023-11-14 16:12:40.679 INFO: Shard ID None has connected to Gateway (Session ID: some-id).
2023-11-14 16:12:44.978 INFO: Generating response for prompt:
you alive?
2023-11-14 16:12:45.189 INFO: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 404 Not Found"
2023-11-14 16:12:45.192 ERROR: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/someUser/.local/lib/python3.8/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "gpt-discord.py", line 83, in on_message
    async for part in await openai_client.chat.completions.create(model=os.environ["GPT_MODEL"], messages=msgs, max_tokens=MAX_COMPLETION_TOKENS, stream=True):
  File "/home/someUser/.local/lib/python3.8/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
  File "/home/someUser/.local/lib/python3.8/site-packages/openai/_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/someUser/.local/lib/python3.8/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
  File "/home/someUser/.local/lib/python3.8/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by jakobdylanc** [comment]
When you select `GPT_MODEL = gpt-4-turbo` in .env, my code remaps it to the real model name (gpt-4-1106-preview). I did this under the assumption that OpenAI will eventually rename the model to gpt-4-turbo, at which point I can push a change to remove the remapping and your .env can stay the same. 

As for your error, it looks like your OpenAI account doesn't have proper access. Your error message includes a link where you can find more info: [](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)
