### ISSUE TITLE
not start sertvice

### ISSUE THREAD

**Issue by DifficultPhil** [jakobdylanc/gpt-discord#7]
ubuntu 22, python 3.10
u can help me?
```
root@gptsher:~/gpt-discord# python gpt-discord.py
Traceback (most recent call last):
  File "/root/gpt-discord/gpt-discord.py", line 7, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "/root/gpt-discord-bot/tutorial-env/lib/python3.10/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/root/gpt-discord-bot/tutorial-env/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/root/gpt-discord-bot/tutorial-env/lib/python3.10/site-packages/tiktoken/load.py", line 117, in load_tiktoken_bpe
    return {
  File "/root/gpt-discord-bot/tutorial-env/lib/python3.10/site-packages/tiktoken/load.py", line 119, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by jakobdylanc** [comment]
Try updating your tiktoken and openai packages via:

`python3.10 -m pip install --upgrade tiktoken`

`python3.10 -m pip install --upgrade openai`

**Comment by DifficultPhil** [comment]
Thanks, it works
